name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Git user identity (optional)
    - name: Set up Git user
      run: |
        git config --global user.email "rekal1417@gmail.com"
        git config --global user.name "onurcangnc"

    # Step 3: Set Heroku remote
    - name: Set Heroku remote
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        # Add the Heroku remote if it doesn't exist
        if ! git remote | grep heroku; then
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
        fi

    # Step 4: Force Push to Heroku
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        git fetch --all --unshallow
        git push heroku main --force
