name: CI/CD Pipeline for Flask App

# Trigger the workflow on push to main or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs to be run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Run tests (add your test framework here)
      - name: Run Tests
        run: |
          pytest  # Assuming you have pytest or some other testing framework

  # Deployment job to Heroku
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Step 3: Deploy to Heroku
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: your-heroku-app-name  # Replace with your Heroku app name
        run: |
          heroku git:remote -a $HEROKU_APP_NAME
          git push heroku main
